name: Build Desktop Apps
on:
  push:
    branches:
      - main

jobs:
  release:
    strategy:
      # Impede que o erro de um sistema cancele o outro
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Atualizamos para a 22 para evitar avisos
          cache: 'npm'

      - name: Install Root Dependencies
        run: npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Build Electron App
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Adicionamos o skip de assinatura (codesigning) para não dar erro no Mac sem licença Apple
          args: --config package.json
        env:
          CSC_LINK: "" # Pula a assinatura de código no Mac
          CSC_IDENTITY_AUTO_DISCOVERY: false