name: Build Desktop Apps
on:
  push:
    branches:
      - main

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Root Dependencies
        run: npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Build Electron App
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Ajuste da Opção 1: apontando para a chave "build" do package.json
          args: "-c.build=package.json" 
        env:
          CSC_LINK: "" 
          CSC_IDENTITY_AUTO_DISCOVERY: false